// Copyright 2024 StarfleetAI
// SPDX-License-Identifier: Apache-2.0

export { default as AgentIcon } from './AgentIcon.vue'
export { default as AgentsIcon } from './AgentsIcon.vue'
export { default as AbilitiesIcon } from './AbilitiesIcon.vue'
export { default as ChatsIcon } from './ChatsIcon.vue'
export { default as CloudIcon } from './CloudIcon.vue'
export { default as DocumentsIcon } from './DocumentsIcon.vue'
export { default as DocumentCheck } from './DocumentCheck.vue'
export { default as DocumentPreview } from './DocumentPreview.vue'
export { default as DocumentTitleIcon } from './DocumentTitleIcon.vue'
export { default as SettingsIcon } from './SettingsIcon.vue'
export { default as TasksIcon } from './TasksIcon.vue'
export { default as SearchIcon } from './SearchIcon.vue'
export { default as NoAvatarIcon } from './NoAvatarIcon.vue'
export { default as TaskStatusDone } from './TaskStatusDone.vue'
export { default as TaskStatusFailed } from './TaskStatusFailed.vue'
export { default as TaskStatusInProgress } from './TaskStatusInProgress.vue'
export { default as TaskStatusNew } from './TaskStatusNew.vue'
export { default as TaskStatusPaused } from './TaskStatusPaused.vue'
export { default as TaskStatusTodo } from './TaskStatusTodo.vue'
export { default as TaskStatusWaiting } from './TaskStatusWaiting.vue'
export { default as FileIcon } from './FileIcon.vue'
export { default as FileTXTIcon } from './FileTXTIcon.vue'
export { default as FileCSVIcon } from './FileCSVIcon.vue'
export { default as TaskHeaderIcon } from './TaskHeaderIcon.vue'
export { default as DocumentIcon } from './DocumentIcon.vue'
export { default as ResultIcon } from './ResultIcon.vue'
export { default as ArrowLeftIcon } from './ArrowLeftIcon.vue'
export { default as FileFrameIcon } from './FileFrameIcon.vue'
export { default as LibraryIcon } from './LibraryIcon.vue'
export { default as StoreIcon } from './StoreIcon.vue'
