name: '[Bridge] Release'

on: workflow_dispatch

jobs:
  release-bridge:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        - platform: 'macos-latest'
          args: '--target aarch64-apple-darwin --features metal'
        - platform: 'macos-latest'
          args: '--target x86_64-apple-darwin'
        - platform: 'ubuntu-20.04'
          args: ''
        - platform: 'windows-latest'
          args: ''
        - platform: 'windows-latest'
          args: '--features cuda'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: install dependencies (ubuntu only)
        if: matrix.settings.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: install frontend dependencies
        run: pnpm i

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: 'v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          args: ${{ matrix.settings.args }}
